backend:
  name: git-gateway
  repo: mcclintsayshi/image-pages
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/media
public_folder: staic/media

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    media_folder: "static/media"
    public_folder: "static/media"
    files:
      - label: "Page"
        name: "apage"
        file: "content/pages/apage.md"
        fields:
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              default: "Shalom Christian Embassy",
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              default: "Our Caption is: WORK HARD PLAY HARD",
            }
          - { label: "Cover Image", name: "image", widget: "image" }
      - label: "Second Page"
        name: "spage"
        file: "content/pages/spage.md"
        fields:
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              default: "Events",
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              default: "Upcoming church events",
            }
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Cover", name: "cover", widget: "image" }
              - { label: "Description", name: "desc", widget: "text" }
